### ISSUE TITLE
Rockspec for version 1.2.2-1 does not mark "after" directory to be copied, so the plugin never loads.

### ISSUE THREAD

**Issue by Invisible-Rabbit-Hunter** [nvim-neorocks/rocks-config.nvim#18]
As the title suggests, the latest version on luarocks, 1.2.2-1, does not have the "after" directory copied, which leads to the plugin not being initialised. and thus no configs are loaded. This is not an issue for version 1.2.1-1, as there the "plugin" directory is marked for copying.

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for reporting.
I have just [merged an API into rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim/pull/209) for extensions like this one to inject behaviour before any plugins are sourced (so that rocks-config can also be used for `vim.g` configuration options).
Once I have published a release, I can implement the hook in rocks-config, and this issue will be solved.

**Comment by mrcjkb** [comment]
https://github.com/nvim-neorocks/rocks-config.nvim/pull/19
